#ifndef JXMPP_JXMPP_H
#define JXMPP_JXMPP_H

#include <JXMPP/AdHoc/OutgoingAdHocCommandSession.h>
#include <JXMPP/Avatars/AvatarManager.h>
#include <JXMPP/Avatars/AvatarManagerImpl.h>
#include <JXMPP/Avatars/AvatarMemoryStorage.h>
#include <JXMPP/Avatars/AvatarProvider.h>
#include <JXMPP/Avatars/AvatarStorage.h>
#include <JXMPP/Avatars/CombinedAvatarProvider.h>
#include <JXMPP/Avatars/DummyAvatarManager.h>
#include <JXMPP/Avatars/NullAvatarManager.h>
#include <JXMPP/Avatars/OfflineAvatarManager.h>
#include <JXMPP/Avatars/VCardAvatarManager.h>
#include <JXMPP/Avatars/VCardUpdateAvatarManager.h>
#include <JXMPP/Base/Algorithm.h>
#include <JXMPP/Base/API.h>
#include <JXMPP/Base/Atomic.h>
#include <JXMPP/Base/BoostFilesystemVersion.h>
#include <JXMPP/Base/ByteArray.h>
#include <JXMPP/Base/Concat.h>
#include <JXMPP/Base/DateTime.h>
#include <JXMPP/Base/Debug.h>
#include <JXMPP/Base/Error.h>
#include <JXMPP/Base/FileSize.h>
#include <JXMPP/Base/IDGenerator.h>
#include <JXMPP/Base/Listenable.h>
#include <JXMPP/Base/LogSerializers.h>
#include <JXMPP/Base/LRUCache.h>
#include <JXMPP/Base/Path.h>
#include <JXMPP/Base/Paths.h>
#include <JXMPP/Base/Platform.h>
#include <JXMPP/Base/RandomGenerator.h>
#include <JXMPP/Base/Regex.h>
#include <JXMPP/Base/SafeAllocator.h>
#include <JXMPP/Base/SafeByteArray.h>
#include <JXMPP/Base/SafeString.h>
#include <JXMPP/Base/SimpleIDGenerator.h>
#include <JXMPP/Base/sleep.h>
#include <JXMPP/Base/StartStopper.h>
#include <JXMPP/Base/StdRandomGenerator.h>
#include <JXMPP/Base/String.h>
#include <JXMPP/Base/Tristate.h>
#include <JXMPP/Base/URL.h>
#include <JXMPP/Chat/ChatStateNotifier.h>
#include <JXMPP/Chat/ChatStateTracker.h>
#include <JXMPP/Client/BlockList.h>
#include <JXMPP/Client/BlockListImpl.h>
#include <JXMPP/Client/Client.h>
#include <JXMPP/Client/ClientBlockListManager.h>
#include <JXMPP/Client/ClientError.h>
#include <JXMPP/Client/ClientOptions.h>
#include <JXMPP/Client/ClientSession.h>
#include <JXMPP/Client/ClientSessionStanzaChannel.h>
#include <JXMPP/Client/ClientXMLTracer.h>
#include <JXMPP/Client/CoreClient.h>
#include <JXMPP/Client/DummyNickManager.h>
#include <JXMPP/Client/DummyStanzaChannel.h>
#include <JXMPP/Client/MemoryStorages.h>
#include <JXMPP/Client/NickManager.h>
#include <JXMPP/Client/NickManagerImpl.h>
#include <JXMPP/Client/NickResolver.h>
#include <JXMPP/Client/StanzaChannel.h>
#include <JXMPP/Client/Storages.h>
#include <JXMPP/Client/XMLBeautifier.h>
#include <JXMPP/Component/Component.h>
#include <JXMPP/Component/ComponentConnector.h>
#include <JXMPP/Component/ComponentError.h>
#include <JXMPP/Component/ComponentHandshakeGenerator.h>
#include <JXMPP/Component/ComponentSession.h>
#include <JXMPP/Component/ComponentSessionStanzaChannel.h>
#include <JXMPP/Component/ComponentXMLTracer.h>
#include <JXMPP/Component/CoreComponent.h>
#include <JXMPP/Compress/ZLibCodecompressor.h>
#include <JXMPP/Compress/ZLibCompressor.h>
#include <JXMPP/Compress/ZLibDecompressor.h>
#include <JXMPP/Compress/ZLibException.h>
#include <JXMPP/Crypto/CommonCryptoCryptoProvider.h>
#include <JXMPP/Crypto/CryptoProvider.h>
#include <JXMPP/Crypto/Hash.h>
#include <JXMPP/Crypto/OpenSSLCryptoProvider.h>
#include <JXMPP/Crypto/PlatformCryptoProvider.h>
#include <JXMPP/Disco/CapsInfoGenerator.h>
#include <JXMPP/Disco/CapsManager.h>
#include <JXMPP/Disco/CapsMemoryStorage.h>
#include <JXMPP/Disco/CapsProvider.h>
#include <JXMPP/Disco/CapsStorage.h>
#include <JXMPP/Disco/ClientDiscoManager.h>
#include <JXMPP/Disco/DiscoInfoResponder.h>
#include <JXMPP/Disco/DiscoServiceWalker.h>
#include <JXMPP/Disco/DummyEntityCapsProvider.h>
#include <JXMPP/Disco/EntityCapsManager.h>
#include <JXMPP/Disco/EntityCapsProvider.h>
#include <JXMPP/Disco/FeatureOracle.h>
#include <JXMPP/Disco/GetDiscoInfoRequest.h>
#include <JXMPP/Disco/GetDiscoItemsRequest.h>
#include <JXMPP/Disco/JIDDiscoInfoResponder.h>
#include <JXMPP/Elements/AuthChallenge.h>
#include <JXMPP/Elements/AuthFailure.h>
#include <JXMPP/Elements/AuthRequest.h>
#include <JXMPP/Elements/AuthResponse.h>
#include <JXMPP/Elements/AuthSuccess.h>
#include <JXMPP/Elements/BlockListPayload.h>
#include <JXMPP/Elements/BlockPayload.h>
#include <JXMPP/Elements/Body.h>
#include <JXMPP/Elements/Bytestreams.h>
#include <JXMPP/Elements/CapsInfo.h>
#include <JXMPP/Elements/CarbonsDisable.h>
#include <JXMPP/Elements/CarbonsEnable.h>
#include <JXMPP/Elements/CarbonsPrivate.h>
#include <JXMPP/Elements/CarbonsReceived.h>
#include <JXMPP/Elements/CarbonsSent.h>
#include <JXMPP/Elements/ChatState.h>
#include <JXMPP/Elements/ClientState.h>
#include <JXMPP/Elements/Command.h>
#include <JXMPP/Elements/ComponentHandshake.h>
#include <JXMPP/Elements/Compressed.h>
#include <JXMPP/Elements/CompressFailure.h>
#include <JXMPP/Elements/CompressRequest.h>
#include <JXMPP/Elements/ContainerPayload.h>
#include <JXMPP/Elements/Delay.h>
#include <JXMPP/Elements/DeliveryReceipt.h>
#include <JXMPP/Elements/DeliveryReceiptRequest.h>
#include <JXMPP/Elements/DiscoInfo.h>
#include <JXMPP/Elements/DiscoItems.h>
#include <JXMPP/Elements/Element.h>
#include <JXMPP/Elements/EnableStreamManagement.h>
#include <JXMPP/Elements/ErrorPayload.h>
#include <JXMPP/Elements/Form.h>
#include <JXMPP/Elements/FormField.h>
#include <JXMPP/Elements/FormPage.h>
#include <JXMPP/Elements/FormReportedRef.h>
#include <JXMPP/Elements/FormSection.h>
#include <JXMPP/Elements/FormText.h>
#include <JXMPP/Elements/Forwarded.h>
#include <JXMPP/Elements/HashElement.h>
#include <JXMPP/Elements/IBB.h>
#include <JXMPP/Elements/Idle.h>
#include <JXMPP/Elements/InBandRegistrationPayload.h>
#include <JXMPP/Elements/IQ.h>
#include <JXMPP/Elements/IsodeIQDelegation.h>
#include <JXMPP/Elements/JingleContentPayload.h>
#include <JXMPP/Elements/JingleDescription.h>
#include <JXMPP/Elements/JingleFileTransferDescription.h>
#include <JXMPP/Elements/JingleFileTransferFileInfo.h>
#include <JXMPP/Elements/JingleFileTransferHash.h>
#include <JXMPP/Elements/JingleIBBTransportPayload.h>
#include <JXMPP/Elements/JinglePayload.h>
#include <JXMPP/Elements/JingleS5BTransportPayload.h>
#include <JXMPP/Elements/JingleTransportPayload.h>
#include <JXMPP/Elements/Last.h>
#include <JXMPP/Elements/MAMFin.h>
#include <JXMPP/Elements/MAMQuery.h>
#include <JXMPP/Elements/MAMResult.h>
#include <JXMPP/Elements/Message.h>
#include <JXMPP/Elements/MIXCreate.h>
#include <JXMPP/Elements/MIXDestroy.h>
#include <JXMPP/Elements/MIXJoin.h>
#include <JXMPP/Elements/MIXLeave.h>
#include <JXMPP/Elements/MIXParticipant.h>
#include <JXMPP/Elements/MIXPayload.h>
#include <JXMPP/Elements/MIXRegisterNick.h>
#include <JXMPP/Elements/MIXSetNick.h>
#include <JXMPP/Elements/MIXUpdateSubscription.h>
#include <JXMPP/Elements/MIXUserPreference.h>
#include <JXMPP/Elements/MUCAdminPayload.h>
#include <JXMPP/Elements/MUCDestroyPayload.h>
#include <JXMPP/Elements/MUCInvitationPayload.h>
#include <JXMPP/Elements/MUCItem.h>
#include <JXMPP/Elements/MUCOccupant.h>
#include <JXMPP/Elements/MUCOwnerPayload.h>
#include <JXMPP/Elements/MUCPayload.h>
#include <JXMPP/Elements/MUCUserPayload.h>
#include <JXMPP/Elements/Nickname.h>
#include <JXMPP/Elements/Payload.h>
#include <JXMPP/Elements/Presence.h>
#include <JXMPP/Elements/Priority.h>
#include <JXMPP/Elements/PrivateStorage.h>
#include <JXMPP/Elements/ProtocolHeader.h>
#include <JXMPP/Elements/PubSub.h>
#include <JXMPP/Elements/PubSubAffiliation.h>
#include <JXMPP/Elements/PubSubAffiliations.h>
#include <JXMPP/Elements/PubSubConfigure.h>
#include <JXMPP/Elements/PubSubCreate.h>
#include <JXMPP/Elements/PubSubDefault.h>
#include <JXMPP/Elements/PubSubError.h>
#include <JXMPP/Elements/PubSubEvent.h>
#include <JXMPP/Elements/PubSubEventAssociate.h>
#include <JXMPP/Elements/PubSubEventCollection.h>
#include <JXMPP/Elements/PubSubEventConfiguration.h>
#include <JXMPP/Elements/PubSubEventDelete.h>
#include <JXMPP/Elements/PubSubEventDisassociate.h>
#include <JXMPP/Elements/PubSubEventItem.h>
#include <JXMPP/Elements/PubSubEventItems.h>
#include <JXMPP/Elements/PubSubEventPayload.h>
#include <JXMPP/Elements/PubSubEventPurge.h>
#include <JXMPP/Elements/PubSubEventRedirect.h>
#include <JXMPP/Elements/PubSubEventRetract.h>
#include <JXMPP/Elements/PubSubEventSubscription.h>
#include <JXMPP/Elements/PubSubItem.h>
#include <JXMPP/Elements/PubSubItems.h>
#include <JXMPP/Elements/PubSubOptions.h>
#include <JXMPP/Elements/PubSubOwnerAffiliation.h>
#include <JXMPP/Elements/PubSubOwnerAffiliations.h>
#include <JXMPP/Elements/PubSubOwnerConfigure.h>
#include <JXMPP/Elements/PubSubOwnerDefault.h>
#include <JXMPP/Elements/PubSubOwnerDelete.h>
#include <JXMPP/Elements/PubSubOwnerPayload.h>
#include <JXMPP/Elements/PubSubOwnerPubSub.h>
#include <JXMPP/Elements/PubSubOwnerPurge.h>
#include <JXMPP/Elements/PubSubOwnerRedirect.h>
#include <JXMPP/Elements/PubSubOwnerSubscription.h>
#include <JXMPP/Elements/PubSubOwnerSubscriptions.h>
#include <JXMPP/Elements/PubSubPayload.h>
#include <JXMPP/Elements/PubSubPublish.h>
#include <JXMPP/Elements/PubSubRetract.h>
#include <JXMPP/Elements/PubSubSubscribe.h>
#include <JXMPP/Elements/PubSubSubscribeOptions.h>
#include <JXMPP/Elements/PubSubSubscription.h>
#include <JXMPP/Elements/PubSubSubscriptions.h>
#include <JXMPP/Elements/PubSubUnsubscribe.h>
#include <JXMPP/Elements/RawXMLPayload.h>
#include <JXMPP/Elements/Replace.h>
#include <JXMPP/Elements/ResourceBind.h>
#include <JXMPP/Elements/ResultSet.h>
#include <JXMPP/Elements/RosterItemExchangePayload.h>
#include <JXMPP/Elements/RosterItemPayload.h>
#include <JXMPP/Elements/RosterPayload.h>
#include <JXMPP/Elements/S5BProxyRequest.h>
#include <JXMPP/Elements/SearchPayload.h>
#include <JXMPP/Elements/SecurityLabel.h>
#include <JXMPP/Elements/SecurityLabelsCatalog.h>
#include <JXMPP/Elements/SoftwareVersion.h>
#include <JXMPP/Elements/Stanza.h>
#include <JXMPP/Elements/StanzaAck.h>
#include <JXMPP/Elements/StanzaAckRequest.h>
#include <JXMPP/Elements/StartSession.h>
#include <JXMPP/Elements/StartTLSFailure.h>
#include <JXMPP/Elements/StartTLSRequest.h>
#include <JXMPP/Elements/Status.h>
#include <JXMPP/Elements/StatusShow.h>
#include <JXMPP/Elements/Storage.h>
#include <JXMPP/Elements/StreamError.h>
#include <JXMPP/Elements/StreamFeatures.h>
#include <JXMPP/Elements/StreamInitiation.h>
#include <JXMPP/Elements/StreamInitiationFileInfo.h>
#include <JXMPP/Elements/StreamManagementEnabled.h>
#include <JXMPP/Elements/StreamManagementFailed.h>
#include <JXMPP/Elements/StreamResume.h>
#include <JXMPP/Elements/StreamResumed.h>
#include <JXMPP/Elements/StreamType.h>
#include <JXMPP/Elements/Subject.h>
#include <JXMPP/Elements/Thread.h>
#include <JXMPP/Elements/TLSProceed.h>
#include <JXMPP/Elements/ToplevelElement.h>
#include <JXMPP/Elements/UnblockPayload.h>
#include <JXMPP/Elements/UnknownElement.h>
#include <JXMPP/Elements/UserLocation.h>
#include <JXMPP/Elements/UserTune.h>
#include <JXMPP/Elements/VCard.h>
#include <JXMPP/Elements/VCardUpdate.h>
#include <JXMPP/Elements/Version.h>
#include <JXMPP/Elements/WhiteboardPayload.h>
#include <JXMPP/Elements/Whiteboard/WhiteboardColor.h>
#include <JXMPP/Elements/Whiteboard/WhiteboardDeleteOperation.h>
#include <JXMPP/Elements/Whiteboard/WhiteboardElement.h>
#include <JXMPP/Elements/Whiteboard/WhiteboardElementVisitor.h>
#include <JXMPP/Elements/Whiteboard/WhiteboardEllipseElement.h>
#include <JXMPP/Elements/Whiteboard/WhiteboardFreehandPathElement.h>
#include <JXMPP/Elements/Whiteboard/WhiteboardInsertOperation.h>
#include <JXMPP/Elements/Whiteboard/WhiteboardLineElement.h>
#include <JXMPP/Elements/Whiteboard/WhiteboardOperation.h>
#include <JXMPP/Elements/Whiteboard/WhiteboardPolygonElement.h>
#include <JXMPP/Elements/Whiteboard/WhiteboardRectElement.h>
#include <JXMPP/Elements/Whiteboard/WhiteboardTextElement.h>
#include <JXMPP/Elements/Whiteboard/WhiteboardUpdateOperation.h>
#include <JXMPP/Entity/Entity.h>
#include <JXMPP/Entity/GenericPayloadPersister.h>
#include <JXMPP/Entity/PayloadPersister.h>
#include <JXMPP/EventLoop/BoostASIOEventLoop.h>
#include <JXMPP/EventLoop/DummyEventLoop.h>
#include <JXMPP/EventLoop/Event.h>
#include <JXMPP/EventLoop/EventLoop.h>
#include <JXMPP/EventLoop/EventOwner.h>
#include <JXMPP/EventLoop/SimpleEventLoop.h>
#include <JXMPP/EventLoop/SingleThreadedEventLoop.h>
#include <JXMPP/FileTransfer/ByteArrayReadBytestream.h>
#include <JXMPP/FileTransfer/ByteArrayWriteBytestream.h>
#include <JXMPP/FileTransfer/BytestreamException.h>
#include <JXMPP/FileTransfer/BytestreamsRequest.h>
#include <JXMPP/FileTransfer/DefaultFileTransferTransporter.h>
#include <JXMPP/FileTransfer/DefaultFileTransferTransporterFactory.h>
#include <JXMPP/FileTransfer/FailingTransportSession.h>
#include <JXMPP/FileTransfer/FileReadBytestream.h>
#include <JXMPP/FileTransfer/FileTransfer.h>
#include <JXMPP/FileTransfer/FileTransferError.h>
#include <JXMPP/FileTransfer/FileTransferManager.h>
#include <JXMPP/FileTransfer/FileTransferManagerImpl.h>
#include <JXMPP/FileTransfer/FileTransferOptions.h>
#include <JXMPP/FileTransfer/FileTransferTransporter.h>
#include <JXMPP/FileTransfer/FileTransferTransporterFactory.h>
#include <JXMPP/FileTransfer/FileWriteBytestream.h>
#include <JXMPP/FileTransfer/IBBReceiveSession.h>
#include <JXMPP/FileTransfer/IBBReceiveTransportSession.h>
#include <JXMPP/FileTransfer/IBBRequest.h>
#include <JXMPP/FileTransfer/IBBSendSession.h>
#include <JXMPP/FileTransfer/IBBSendTransportSession.h>
#include <JXMPP/FileTransfer/IncomingFileTransfer.h>
#include <JXMPP/FileTransfer/IncomingFileTransferManager.h>
#include <JXMPP/FileTransfer/IncomingJingleFileTransfer.h>
#include <JXMPP/FileTransfer/IncrementalBytestreamHashCalculator.h>
#include <JXMPP/FileTransfer/JingleFileTransfer.h>
#include <JXMPP/FileTransfer/LocalJingleTransportCandidateGenerator.h>
#include <JXMPP/FileTransfer/OutgoingFileTransfer.h>
#include <JXMPP/FileTransfer/OutgoingFileTransferManager.h>
#include <JXMPP/FileTransfer/OutgoingJingleFileTransfer.h>
#include <JXMPP/FileTransfer/ReadBytestream.h>
#include <JXMPP/FileTransfer/RemoteJingleTransportCandidateSelector.h>
#include <JXMPP/FileTransfer/S5BTransportSession.h>
#include <JXMPP/FileTransfer/SOCKS5BytestreamClientSession.h>
#include <JXMPP/FileTransfer/SOCKS5BytestreamProxiesManager.h>
#include <JXMPP/FileTransfer/SOCKS5BytestreamProxyFinder.h>
#include <JXMPP/FileTransfer/SOCKS5BytestreamRegistry.h>
#include <JXMPP/FileTransfer/SOCKS5BytestreamServer.h>
#include <JXMPP/FileTransfer/SOCKS5BytestreamServerManager.h>
#include <JXMPP/FileTransfer/SOCKS5BytestreamServerPortForwardingUser.h>
#include <JXMPP/FileTransfer/SOCKS5BytestreamServerResourceUser.h>
#include <JXMPP/FileTransfer/SOCKS5BytestreamServerSession.h>
#include <JXMPP/FileTransfer/StreamInitiationRequest.h>
#include <JXMPP/FileTransfer/TransportSession.h>
#include <JXMPP/FileTransfer/WriteBytestream.h>
#include <JXMPP/History/HistoryMessage.h>
#include <JXMPP/History/HistoryStorage.h>
#include <JXMPP/IDN/IDNConverter.h>
#include <JXMPP/IDN/LibIDNConverter.h>
#include <JXMPP/IDN/PlatformIDNConverter.h>
#include <JXMPP/IDN/UTF8Validator.h>
#include <JXMPP/JID/JID.h>
#include <JXMPP/Jingle/AbstractJingleSessionListener.h>
#include <JXMPP/Jingle/FakeJingleSession.h>
#include <JXMPP/Jingle/IncomingJingleSessionHandler.h>
#include <JXMPP/Jingle/Jingle.h>
#include <JXMPP/Jingle/JingleContentID.h>
#include <JXMPP/Jingle/JingleResponder.h>
#include <JXMPP/Jingle/JingleSession.h>
#include <JXMPP/Jingle/JingleSessionImpl.h>
#include <JXMPP/Jingle/JingleSessionListener.h>
#include <JXMPP/Jingle/JingleSessionManager.h>
#include <JXMPP/LinkLocal/IncomingLinkLocalSession.h>
#include <JXMPP/LinkLocal/LinkLocalConnector.h>
#include <JXMPP/LinkLocal/LinkLocalService.h>
#include <JXMPP/LinkLocal/LinkLocalServiceBrowser.h>
#include <JXMPP/LinkLocal/LinkLocalServiceInfo.h>
#include <JXMPP/LinkLocal/OutgoingLinkLocalSession.h>
#include <JXMPP/LinkLocal/DNSSD/DNSSDBrowseQuery.h>
#include <JXMPP/LinkLocal/DNSSD/DNSSDQuerier.h>
#include <JXMPP/LinkLocal/DNSSD/DNSSDRegisterQuery.h>
#include <JXMPP/LinkLocal/DNSSD/DNSSDResolveHostnameQuery.h>
#include <JXMPP/LinkLocal/DNSSD/DNSSDResolveServiceQuery.h>
#include <JXMPP/LinkLocal/DNSSD/DNSSDServiceID.h>
#include <JXMPP/LinkLocal/DNSSD/PlatformDNSSDQuerierFactory.h>
#include <JXMPP/LinkLocal/DNSSD/Fake/FakeDNSSDBrowseQuery.h>
#include <JXMPP/LinkLocal/DNSSD/Fake/FakeDNSSDQuerier.h>
#include <JXMPP/LinkLocal/DNSSD/Fake/FakeDNSSDQuery.h>
#include <JXMPP/LinkLocal/DNSSD/Fake/FakeDNSSDRegisterQuery.h>
#include <JXMPP/LinkLocal/DNSSD/Fake/FakeDNSSDResolveHostnameQuery.h>
#include <JXMPP/LinkLocal/DNSSD/Fake/FakeDNSSDResolveServiceQuery.h>
#include <JXMPP/MIX/MIX.h>
#include <JXMPP/MIX/MIXImpl.h>
#include <JXMPP/MUC/MUC.h>
#include <JXMPP/MUC/MUCBookmark.h>
#include <JXMPP/MUC/MUCBookmarkManager.h>
#include <JXMPP/MUC/MUCImpl.h>
#include <JXMPP/MUC/MUCManager.h>
#include <JXMPP/MUC/MUCRegistry.h>
#include <JXMPP/Network/BoostConnection.h>
#include <JXMPP/Network/BoostConnectionFactory.h>
#include <JXMPP/Network/BoostConnectionServer.h>
#include <JXMPP/Network/BoostConnectionServerFactory.h>
#include <JXMPP/Network/BoostIOServiceThread.h>
#include <JXMPP/Network/BoostNetworkFactories.h>
#include <JXMPP/Network/BoostTimer.h>
#include <JXMPP/Network/BoostTimerFactory.h>
#include <JXMPP/Network/BOSHConnection.h>
#include <JXMPP/Network/BOSHConnectionPool.h>
#include <JXMPP/Network/CachingDomainNameResolver.h>
#include <JXMPP/Network/ChainedConnector.h>
#include <JXMPP/Network/Connection.h>
#include <JXMPP/Network/ConnectionFactory.h>
#include <JXMPP/Network/ConnectionServer.h>
#include <JXMPP/Network/ConnectionServerFactory.h>
#include <JXMPP/Network/Connector.h>
#include <JXMPP/Network/DomainNameAddressQuery.h>
#include <JXMPP/Network/DomainNameResolveError.h>
#include <JXMPP/Network/DomainNameResolver.h>
#include <JXMPP/Network/DomainNameServiceQuery.h>
#include <JXMPP/Network/DummyConnection.h>
#include <JXMPP/Network/DummyConnectionFactory.h>
#include <JXMPP/Network/DummyConnectionServer.h>
#include <JXMPP/Network/DummyConnectionServerFactory.h>
#include <JXMPP/Network/DummyTimerFactory.h>
#include <JXMPP/Network/EnvironmentProxyProvider.h>
#include <JXMPP/Network/FakeConnection.h>
#include <JXMPP/Network/GConfProxyProvider.h>
#include <JXMPP/Network/HostAddress.h>
#include <JXMPP/Network/HostAddressPort.h>
#include <JXMPP/Network/HostNameOrAddress.h>
#include <JXMPP/Network/HTTPConnectProxiedConnection.h>
#include <JXMPP/Network/HTTPConnectProxiedConnectionFactory.h>
#include <JXMPP/Network/HTTPTrafficFilter.h>
#include <JXMPP/Network/MiniUPnPInterface.h>
#include <JXMPP/Network/NATPMPInterface.h>
#include <JXMPP/Network/NATPortMapping.h>
#include <JXMPP/Network/NATTraversalForwardPortRequest.h>
#include <JXMPP/Network/NATTraversalGetPublicIPRequest.h>
#include <JXMPP/Network/NATTraversalInterface.h>
#include <JXMPP/Network/NATTraversalRemovePortForwardingRequest.h>
#include <JXMPP/Network/NATTraverser.h>
#include <JXMPP/Network/NetworkEnvironment.h>
#include <JXMPP/Network/NetworkFactories.h>
#include <JXMPP/Network/NetworkInterface.h>
#include <JXMPP/Network/NullNATTraversalInterface.h>
#include <JXMPP/Network/NullNATTraverser.h>
#include <JXMPP/Network/NullProxyProvider.h>
#include <JXMPP/Network/PlatformDomainNameAddressQuery.h>
#include <JXMPP/Network/PlatformDomainNameQuery.h>
#include <JXMPP/Network/PlatformDomainNameResolver.h>
#include <JXMPP/Network/PlatformDomainNameServiceQuery.h>
#include <JXMPP/Network/PlatformNATTraversalWorker.h>
#include <JXMPP/Network/PlatformNetworkEnvironment.h>
#include <JXMPP/Network/PlatformProxyProvider.h>
#include <JXMPP/Network/ProxiedConnection.h>
#include <JXMPP/Network/ProxyProvider.h>
#include <JXMPP/Network/SOCKS5ProxiedConnection.h>
#include <JXMPP/Network/SOCKS5ProxiedConnectionFactory.h>
#include <JXMPP/Network/SolarisNetworkEnvironment.h>
#include <JXMPP/Network/StaticDomainNameResolver.h>
#include <JXMPP/Network/Timer.h>
#include <JXMPP/Network/TimerFactory.h>
#include <JXMPP/Network/TLSConnection.h>
#include <JXMPP/Network/TLSConnectionFactory.h>
#include <JXMPP/Network/UnixNetworkEnvironment.h>
#include <JXMPP/Network/UnixProxyProvider.h>
#include <JXMPP/Parser/Attribute.h>
#include <JXMPP/Parser/AttributeMap.h>
#include <JXMPP/Parser/AuthChallengeParser.h>
#include <JXMPP/Parser/AuthFailureParser.h>
#include <JXMPP/Parser/AuthRequestParser.h>
#include <JXMPP/Parser/AuthResponseParser.h>
#include <JXMPP/Parser/AuthSuccessParser.h>
#include <JXMPP/Parser/BOSHBodyExtractor.h>
#include <JXMPP/Parser/ComponentHandshakeParser.h>
#include <JXMPP/Parser/CompressedParser.h>
#include <JXMPP/Parser/CompressFailureParser.h>
#include <JXMPP/Parser/CompressParser.h>
#include <JXMPP/Parser/ElementParser.h>
#include <JXMPP/Parser/EnableStreamManagementParser.h>
#include <JXMPP/Parser/EnumParser.h>
#include <JXMPP/Parser/ExpatParser.h>
#include <JXMPP/Parser/GenericElementParser.h>
#include <JXMPP/Parser/GenericPayloadParser.h>
#include <JXMPP/Parser/GenericPayloadParserFactory.h>
#include <JXMPP/Parser/GenericPayloadParserFactory2.h>
#include <JXMPP/Parser/GenericPayloadTreeParser.h>
#include <JXMPP/Parser/GenericStanzaParser.h>
#include <JXMPP/Parser/IQParser.h>
#include <JXMPP/Parser/LibXMLParser.h>
#include <JXMPP/Parser/MessageParser.h>
#include <JXMPP/Parser/PayloadParser.h>
#include <JXMPP/Parser/PayloadParserFactory.h>
#include <JXMPP/Parser/PayloadParserFactoryCollection.h>
#include <JXMPP/Parser/PlatformXMLParserFactory.h>
#include <JXMPP/Parser/PresenceParser.h>
#include <JXMPP/Parser/SerializingParser.h>
#include <JXMPP/Parser/StanzaAckParser.h>
#include <JXMPP/Parser/StanzaAckRequestParser.h>
#include <JXMPP/Parser/StanzaParser.h>
#include <JXMPP/Parser/StartTLSFailureParser.h>
#include <JXMPP/Parser/StartTLSParser.h>
#include <JXMPP/Parser/StreamErrorParser.h>
#include <JXMPP/Parser/StreamFeaturesParser.h>
#include <JXMPP/Parser/StreamManagementEnabledParser.h>
#include <JXMPP/Parser/StreamManagementFailedParser.h>
#include <JXMPP/Parser/StreamResumedParser.h>
#include <JXMPP/Parser/StreamResumeParser.h>
#include <JXMPP/Parser/TLSProceedParser.h>
#include <JXMPP/Parser/UnknownElementParser.h>
#include <JXMPP/Parser/UnknownPayloadParser.h>
#include <JXMPP/Parser/XMLParser.h>
#include <JXMPP/Parser/XMLParserClient.h>
#include <JXMPP/Parser/XMLParserFactory.h>
#include <JXMPP/Parser/XMPPParser.h>
#include <JXMPP/Parser/XMPPParserClient.h>
#include <JXMPP/Parser/PayloadParsers/BlockParser.h>
#include <JXMPP/Parser/PayloadParsers/BodyParser.h>
#include <JXMPP/Parser/PayloadParsers/BytestreamsParser.h>
#include <JXMPP/Parser/PayloadParsers/CapsInfoParser.h>
#include <JXMPP/Parser/PayloadParsers/CarbonsDisableParser.h>
#include <JXMPP/Parser/PayloadParsers/CarbonsEnableParser.h>
#include <JXMPP/Parser/PayloadParsers/CarbonsPrivateParser.h>
#include <JXMPP/Parser/PayloadParsers/CarbonsReceivedParser.h>
#include <JXMPP/Parser/PayloadParsers/CarbonsSentParser.h>
#include <JXMPP/Parser/PayloadParsers/ChatStateParser.h>
#include <JXMPP/Parser/PayloadParsers/ChatStateParserFactory.h>
#include <JXMPP/Parser/PayloadParsers/ClientStateParser.h>
#include <JXMPP/Parser/PayloadParsers/ClientStateParserFactory.h>
#include <JXMPP/Parser/PayloadParsers/CommandParser.h>
#include <JXMPP/Parser/PayloadParsers/DelayParser.h>
#include <JXMPP/Parser/PayloadParsers/DeliveryReceiptParser.h>
#include <JXMPP/Parser/PayloadParsers/DeliveryReceiptParserFactory.h>
#include <JXMPP/Parser/PayloadParsers/DeliveryReceiptRequestParser.h>
#include <JXMPP/Parser/PayloadParsers/DeliveryReceiptRequestParserFactory.h>
#include <JXMPP/Parser/PayloadParsers/DiscoInfoParser.h>
#include <JXMPP/Parser/PayloadParsers/DiscoItemsParser.h>
#include <JXMPP/Parser/PayloadParsers/ErrorParser.h>
#include <JXMPP/Parser/PayloadParsers/ErrorParserFactory.h>
#include <JXMPP/Parser/PayloadParsers/FormParser.h>
#include <JXMPP/Parser/PayloadParsers/FormParserFactory.h>
#include <JXMPP/Parser/PayloadParsers/ForwardedParser.h>
#include <JXMPP/Parser/PayloadParsers/FullPayloadParserFactoryCollection.h>
#include <JXMPP/Parser/PayloadParsers/IBBParser.h>
#include <JXMPP/Parser/PayloadParsers/IdleParser.h>
#include <JXMPP/Parser/PayloadParsers/InBandRegistrationPayloadParser.h>
#include <JXMPP/Parser/PayloadParsers/IsodeIQDelegationParser.h>
#include <JXMPP/Parser/PayloadParsers/JingleContentPayloadParser.h>
#include <JXMPP/Parser/PayloadParsers/JingleContentPayloadParserFactory.h>
#include <JXMPP/Parser/PayloadParsers/JingleFileTransferDescriptionParser.h>
#include <JXMPP/Parser/PayloadParsers/JingleFileTransferDescriptionParserFactory.h>
#include <JXMPP/Parser/PayloadParsers/JingleFileTransferFileInfoParser.h>
#include <JXMPP/Parser/PayloadParsers/JingleFileTransferHashParser.h>
#include <JXMPP/Parser/PayloadParsers/JingleIBBTransportMethodPayloadParser.h>
#include <JXMPP/Parser/PayloadParsers/JingleParser.h>
#include <JXMPP/Parser/PayloadParsers/JingleParserFactory.h>
#include <JXMPP/Parser/PayloadParsers/JingleReasonParser.h>
#include <JXMPP/Parser/PayloadParsers/JingleS5BTransportMethodPayloadParser.h>
#include <JXMPP/Parser/PayloadParsers/LastParser.h>
#include <JXMPP/Parser/PayloadParsers/MAMFinParser.h>
#include <JXMPP/Parser/PayloadParsers/MAMQueryParser.h>
#include <JXMPP/Parser/PayloadParsers/MAMResultParser.h>
#include <JXMPP/Parser/PayloadParsers/MIXCreateParser.h>
#include <JXMPP/Parser/PayloadParsers/MIXDestroyParser.h>
#include <JXMPP/Parser/PayloadParsers/MIXJoinParser.h>
#include <JXMPP/Parser/PayloadParsers/MIXJoinParserFactory.h>
#include <JXMPP/Parser/PayloadParsers/MIXLeaveParser.h>
#include <JXMPP/Parser/PayloadParsers/MIXParticipantParser.h>
#include <JXMPP/Parser/PayloadParsers/MIXParticipantParserFactory.h>
#include <JXMPP/Parser/PayloadParsers/MIXPayloadParser.h>
#include <JXMPP/Parser/PayloadParsers/MIXPayloadParserFactory.h>
#include <JXMPP/Parser/PayloadParsers/MIXRegisterNickParser.h>
#include <JXMPP/Parser/PayloadParsers/MIXRegisterNickParserFactory.h>
#include <JXMPP/Parser/PayloadParsers/MIXSetNickParser.h>
#include <JXMPP/Parser/PayloadParsers/MIXSetNickParserFactory.h>
#include <JXMPP/Parser/PayloadParsers/MIXUpdateSubscriptionParser.h>
#include <JXMPP/Parser/PayloadParsers/MIXUserPreferenceParser.h>
#include <JXMPP/Parser/PayloadParsers/MUCAdminPayloadParser.h>
#include <JXMPP/Parser/PayloadParsers/MUCDestroyPayloadParser.h>
#include <JXMPP/Parser/PayloadParsers/MUCInvitationPayloadParser.h>
#include <JXMPP/Parser/PayloadParsers/MUCItemParser.h>
#include <JXMPP/Parser/PayloadParsers/MUCOwnerPayloadParser.h>
#include <JXMPP/Parser/PayloadParsers/MUCOwnerPayloadParserFactory.h>
#include <JXMPP/Parser/PayloadParsers/MUCUserPayloadParser.h>
#include <JXMPP/Parser/PayloadParsers/MUCUserPayloadParserFactory.h>
#include <JXMPP/Parser/PayloadParsers/NicknameParser.h>
#include <JXMPP/Parser/PayloadParsers/PriorityParser.h>
#include <JXMPP/Parser/PayloadParsers/PrivateStorageParser.h>
#include <JXMPP/Parser/PayloadParsers/PrivateStorageParserFactory.h>
#include <JXMPP/Parser/PayloadParsers/PubSubAffiliationParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubAffiliationsParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubConfigureParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubCreateParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubDefaultParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubErrorParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubErrorParserFactory.h>
#include <JXMPP/Parser/PayloadParsers/PubSubEventAssociateParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubEventCollectionParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubEventConfigurationParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubEventDeleteParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubEventDisassociateParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubEventItemParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubEventItemsParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubEventParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubEventPurgeParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubEventRedirectParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubEventRetractParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubEventSubscriptionParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubItemParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubItemsParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubOptionsParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubOwnerAffiliationParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubOwnerAffiliationsParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubOwnerConfigureParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubOwnerDefaultParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubOwnerDeleteParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubOwnerPubSubParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubOwnerPurgeParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubOwnerRedirectParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubOwnerSubscriptionParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubOwnerSubscriptionsParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubPublishParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubRetractParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubSubscribeOptionsParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubSubscribeParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubSubscriptionParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubSubscriptionsParser.h>
#include <JXMPP/Parser/PayloadParsers/PubSubUnsubscribeParser.h>
#include <JXMPP/Parser/PayloadParsers/RawXMLPayloadParser.h>
#include <JXMPP/Parser/PayloadParsers/RawXMLPayloadParserFactory.h>
#include <JXMPP/Parser/PayloadParsers/ReplaceParser.h>
#include <JXMPP/Parser/PayloadParsers/ResourceBindParser.h>
#include <JXMPP/Parser/PayloadParsers/ResultSetParser.h>
#include <JXMPP/Parser/PayloadParsers/RosterItemExchangeParser.h>
#include <JXMPP/Parser/PayloadParsers/RosterParser.h>
#include <JXMPP/Parser/PayloadParsers/S5BProxyRequestParser.h>
#include <JXMPP/Parser/PayloadParsers/SearchPayloadParser.h>
#include <JXMPP/Parser/PayloadParsers/SecurityLabelParser.h>
#include <JXMPP/Parser/PayloadParsers/SecurityLabelParserFactory.h>
#include <JXMPP/Parser/PayloadParsers/SecurityLabelsCatalogParser.h>
#include <JXMPP/Parser/PayloadParsers/SoftwareVersionParser.h>
#include <JXMPP/Parser/PayloadParsers/StartSessionParser.h>
#include <JXMPP/Parser/PayloadParsers/StatusParser.h>
#include <JXMPP/Parser/PayloadParsers/StatusShowParser.h>
#include <JXMPP/Parser/PayloadParsers/StorageParser.h>
#include <JXMPP/Parser/PayloadParsers/StreamInitiationFileInfoParser.h>
#include <JXMPP/Parser/PayloadParsers/StreamInitiationParser.h>
#include <JXMPP/Parser/PayloadParsers/SubjectParser.h>
#include <JXMPP/Parser/PayloadParsers/ThreadParser.h>
#include <JXMPP/Parser/PayloadParsers/UserLocationParser.h>
#include <JXMPP/Parser/PayloadParsers/UserTuneParser.h>
#include <JXMPP/Parser/PayloadParsers/VCardParser.h>
#include <JXMPP/Parser/PayloadParsers/VCardUpdateParser.h>
#include <JXMPP/Parser/PayloadParsers/WhiteboardParser.h>
#include <JXMPP/Parser/Tree/NullParserElement.h>
#include <JXMPP/Parser/Tree/ParserElement.h>
#include <JXMPP/Parser/Tree/TreeReparser.h>
#include <JXMPP/Presence/DirectedPresenceSender.h>
#include <JXMPP/Presence/PayloadAddingPresenceSender.h>
#include <JXMPP/Presence/PresenceOracle.h>
#include <JXMPP/Presence/PresenceSender.h>
#include <JXMPP/Presence/StanzaChannelPresenceSender.h>
#include <JXMPP/Presence/SubscriptionManager.h>
#include <JXMPP/PubSub/PubSubManager.h>
#include <JXMPP/PubSub/PubSubManagerImpl.h>
#include <JXMPP/PubSub/PubSubUtil.h>
#include <JXMPP/Queries/DummyIQChannel.h>
#include <JXMPP/Queries/GenericRequest.h>
#include <JXMPP/Queries/GetResponder.h>
#include <JXMPP/Queries/IQChannel.h>
#include <JXMPP/Queries/IQHandler.h>
#include <JXMPP/Queries/IQRouter.h>
#include <JXMPP/Queries/PubSubRequest.h>
#include <JXMPP/Queries/RawRequest.h>
#include <JXMPP/Queries/Request.h>
#include <JXMPP/Queries/Responder.h>
#include <JXMPP/Queries/SetResponder.h>
#include <JXMPP/Queries/Requests/EnableCarbonsRequest.h>
#include <JXMPP/Queries/Requests/GetInBandRegistrationFormRequest.h>
#include <JXMPP/Queries/Requests/GetPrivateStorageRequest.h>
#include <JXMPP/Queries/Requests/GetSecurityLabelsCatalogRequest.h>
#include <JXMPP/Queries/Requests/GetSoftwareVersionRequest.h>
#include <JXMPP/Queries/Requests/SetPrivateStorageRequest.h>
#include <JXMPP/Queries/Requests/SubmitInBandRegistrationFormRequest.h>
#include <JXMPP/Queries/Responders/SoftwareVersionResponder.h>
#include <JXMPP/Roster/GetRosterRequest.h>
#include <JXMPP/Roster/RosterMemoryStorage.h>
#include <JXMPP/Roster/RosterPushResponder.h>
#include <JXMPP/Roster/RosterStorage.h>
#include <JXMPP/Roster/SetRosterRequest.h>
#include <JXMPP/Roster/XMPPRoster.h>
#include <JXMPP/Roster/XMPPRosterController.h>
#include <JXMPP/Roster/XMPPRosterImpl.h>
#include <JXMPP/Roster/XMPPRosterItem.h>
#include <JXMPP/SASL/ClientAuthenticator.h>
#include <JXMPP/SASL/DIGESTMD5ClientAuthenticator.h>
#include <JXMPP/SASL/DIGESTMD5Properties.h>
#include <JXMPP/SASL/EXTERNALClientAuthenticator.h>
#include <JXMPP/SASL/PLAINClientAuthenticator.h>
#include <JXMPP/SASL/PLAINMessage.h>
#include <JXMPP/SASL/SCRAMSHA1ClientAuthenticator.h>
#include <JXMPP/Serializer/AuthChallengeSerializer.h>
#include <JXMPP/Serializer/AuthFailureSerializer.h>
#include <JXMPP/Serializer/AuthRequestSerializer.h>
#include <JXMPP/Serializer/AuthResponseSerializer.h>
#include <JXMPP/Serializer/AuthSuccessSerializer.h>
#include <JXMPP/Serializer/ComponentHandshakeSerializer.h>
#include <JXMPP/Serializer/CompressFailureSerializer.h>
#include <JXMPP/Serializer/CompressRequestSerializer.h>
#include <JXMPP/Serializer/ElementSerializer.h>
#include <JXMPP/Serializer/EnableStreamManagementSerializer.h>
#include <JXMPP/Serializer/GenericElementSerializer.h>
#include <JXMPP/Serializer/GenericPayloadSerializer.h>
#include <JXMPP/Serializer/GenericStanzaSerializer.h>
#include <JXMPP/Serializer/IQSerializer.h>
#include <JXMPP/Serializer/MessageSerializer.h>
#include <JXMPP/Serializer/PayloadSerializer.h>
#include <JXMPP/Serializer/PayloadSerializerCollection.h>
#include <JXMPP/Serializer/PresenceSerializer.h>
#include <JXMPP/Serializer/StanzaAckRequestSerializer.h>
#include <JXMPP/Serializer/StanzaAckSerializer.h>
#include <JXMPP/Serializer/StanzaSerializer.h>
#include <JXMPP/Serializer/StartTLSFailureSerializer.h>
#include <JXMPP/Serializer/StartTLSRequestSerializer.h>
#include <JXMPP/Serializer/StreamErrorSerializer.h>
#include <JXMPP/Serializer/StreamFeaturesSerializer.h>
#include <JXMPP/Serializer/StreamManagementEnabledSerializer.h>
#include <JXMPP/Serializer/StreamManagementFailedSerializer.h>
#include <JXMPP/Serializer/StreamResumedSerializer.h>
#include <JXMPP/Serializer/StreamResumeSerializer.h>
#include <JXMPP/Serializer/TLSProceedSerializer.h>
#include <JXMPP/Serializer/XMPPSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/BlockSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/BodySerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/BytestreamsSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/CapsInfoSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/CarbonsDisableSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/CarbonsEnableSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/CarbonsPrivateSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/CarbonsReceivedSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/CarbonsSentSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/ChatStateSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/ClientStateSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/CommandSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/DelaySerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/DeliveryReceiptRequestSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/DeliveryReceiptSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/DiscoInfoSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/DiscoItemsSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/ErrorSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/FormSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/ForwardedSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/FullPayloadSerializerCollection.h>
#include <JXMPP/Serializer/PayloadSerializers/IBBSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/IdleSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/InBandRegistrationPayloadSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/IsodeIQDelegationSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/JingleContentPayloadSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/JingleFileTransferDescriptionSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/JingleFileTransferFileInfoSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/JingleFileTransferHashSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/JingleIBBTransportPayloadSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/JinglePayloadSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/JingleS5BTransportPayloadSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/LastSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/MAMFinSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/MAMQuerySerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/MAMResultSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/MIXCreateSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/MIXDestroySerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/MIXJoinSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/MIXLeaveSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/MIXParticipantSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/MIXPayloadSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/MIXRegisterNickSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/MIXSetNickSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/MIXUpdateSubscriptionSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/MIXUserPreferenceSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/MUCAdminPayloadSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/MUCDestroyPayloadSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/MUCInvitationPayloadSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/MUCItemSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/MUCOwnerPayloadSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/MUCPayloadSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/MUCUserPayloadSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/NicknameSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PrioritySerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PrivateStorageSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubAffiliationSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubAffiliationsSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubConfigureSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubCreateSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubDefaultSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubErrorSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubEventAssociateSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubEventCollectionSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubEventConfigurationSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubEventDeleteSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubEventDisassociateSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubEventItemSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubEventItemsSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubEventPurgeSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubEventRedirectSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubEventRetractSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubEventSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubEventSubscriptionSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubItemSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubItemsSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubOptionsSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubOwnerAffiliationSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubOwnerAffiliationsSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubOwnerConfigureSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubOwnerDefaultSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubOwnerDeleteSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubOwnerPubSubSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubOwnerPurgeSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubOwnerRedirectSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubOwnerSubscriptionSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubOwnerSubscriptionsSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubPublishSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubRetractSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubSubscribeOptionsSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubSubscribeSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubSubscriptionSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubSubscriptionsSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/PubSubUnsubscribeSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/RawXMLPayloadSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/ReplaceSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/ResourceBindSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/ResultSetSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/RosterItemExchangeSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/RosterSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/S5BProxyRequestSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/SearchPayloadSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/SecurityLabelsCatalogSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/SecurityLabelSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/SoftwareVersionSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/StartSessionSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/StatusSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/StatusShowSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/StorageSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/StreamInitiationFileInfoSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/StreamInitiationSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/SubjectSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/ThreadSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/UserLocationSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/UserTuneSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/VCardSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/VCardUpdateSerializer.h>
#include <JXMPP/Serializer/PayloadSerializers/WhiteboardSerializer.h>
#include <JXMPP/Serializer/XML/XMLElement.h>
#include <JXMPP/Serializer/XML/XMLNode.h>
#include <JXMPP/Serializer/XML/XMLRawTextNode.h>
#include <JXMPP/Serializer/XML/XMLTextNode.h>
#include <JXMPP/Session/BasicSessionStream.h>
#include <JXMPP/Session/BOSHSessionStream.h>
#include <JXMPP/Session/Session.h>
#include <JXMPP/Session/SessionStream.h>
#include <JXMPP/Session/SessionTracer.h>
#include <JXMPP/StreamManagement/StanzaAckRequester.h>
#include <JXMPP/StreamManagement/StanzaAckResponder.h>
#include <JXMPP/StreamStack/CompressionLayer.h>
#include <JXMPP/StreamStack/ConnectionLayer.h>
#include <JXMPP/StreamStack/DummyStreamLayer.h>
#include <JXMPP/StreamStack/HighLayer.h>
#include <JXMPP/StreamStack/LowLayer.h>
#include <JXMPP/StreamStack/StreamLayer.h>
#include <JXMPP/StreamStack/StreamStack.h>
#include <JXMPP/StreamStack/TLSLayer.h>
#include <JXMPP/StreamStack/WhitespacePingLayer.h>
#include <JXMPP/StreamStack/XMPPLayer.h>
#include <JXMPP/StringCodecs/Base64.h>
#include <JXMPP/StringCodecs/Hexify.h>
#include <JXMPP/StringCodecs/PBKDF2.h>
#include <JXMPP/TLS/BlindCertificateTrustChecker.h>
#include <JXMPP/TLS/Certificate.h>
#include <JXMPP/TLS/CertificateFactory.h>
#include <JXMPP/TLS/CertificateTrustChecker.h>
#include <JXMPP/TLS/CertificateVerificationError.h>
#include <JXMPP/TLS/CertificateWithKey.h>
#include <JXMPP/TLS/PKCS12Certificate.h>
#include <JXMPP/TLS/PlatformTLSFactories.h>
#include <JXMPP/TLS/ServerIdentityVerifier.h>
#include <JXMPP/TLS/SimpleCertificate.h>
#include <JXMPP/TLS/TLSContext.h>
#include <JXMPP/TLS/TLSContextFactory.h>
#include <JXMPP/TLS/TLSError.h>
#include <JXMPP/TLS/TLSOptions.h>
#include <JXMPP/VCards/GetVCardRequest.h>
#include <JXMPP/VCards/SetVCardRequest.h>
#include <JXMPP/VCards/VCardManager.h>
#include <JXMPP/VCards/VCardMemoryStorage.h>
#include <JXMPP/VCards/VCardStorage.h>
#include <JXMPP/Whiteboard/IncomingWhiteboardSession.h>
#include <JXMPP/Whiteboard/OutgoingWhiteboardSession.h>
#include <JXMPP/Whiteboard/WhiteboardClient.h>
#include <JXMPP/Whiteboard/WhiteboardResponder.h>
#include <JXMPP/Whiteboard/WhiteboardServer.h>
#include <JXMPP/Whiteboard/WhiteboardSession.h>
#include <JXMPP/Whiteboard/WhiteboardSessionManager.h>
#include <JXMPP/Whiteboard/WhiteboardTransformer.h>

#endif // JXMPP_JXMPP_H
