#ifndef JXMPP_BOOSTFILESYSTEMVERSION_H
#define JXMPP_BOOSTFILESYSTEMVERSION_H

#ifndef BOOST_FILESYSTEM_VERSION
#define BOOST_FILESYSTEM_VERSION 2
#endif

#endif // JXMPP_BOOSTFILESYSTEMVERSION_H
